import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { type FunctionComponent } from 'react'
import AuthSessionProvider from '@/context/providers/authSession.provider'
import NextUiProvider from '@/context/providers/nextUI.provider'
import SWRProvider from '@/context/providers/swr.provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface Props {
  children: React.ReactNode
}

const RootLayout: FunctionComponent<Props> = ({ children }: { children: React.ReactNode }) => (
  <html lang='en'>
    <body className={inter.className}>
      <AuthSessionProvider>
        <NextUiProvider>
          <SWRProvider>{children}</SWRProvider>
        </NextUiProvider>
      </AuthSessionProvider>
    </body>
  </html>
)

export default RootLayout
